"""Initial migration

Revision ID: 0a78b41a9c69
Revises:
Create Date: 2026-07-16 15:17:50.707381

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a78b41a9c69"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oil_companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("region", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lName", sa.String(length=255), nullable=False),
        sa.Column("fName", sa.String(length=255), nullable=False),
        sa.Column("oil_company_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["oil_company_id"],
            ["oil_companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wells",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column("max_drilling_depth", sa.Float(), nullable=False),
        sa.Column("oil_company_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["oil_company_id"],
            ["oil_companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "daily_productions",
        sa.Column("well_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("operating_hours", sa.Float(), nullable=False),
        sa.Column("liquid_produced", sa.Float(), nullable=False),
        sa.Column("water_cut", sa.Float(), nullable=False),
        sa.Column("density", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["well_id"],
            ["wells.id"],
        ),
        sa.PrimaryKeyConstraint("well_id", "date"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daily_productions")
    op.drop_table("wells")
    op.drop_table("users")
    op.drop_table("oil_companies")
    # ### end Alembic commands ###
